export const PURCHASE_ORDER_SUCCESS = "PURCHASE_ORDER_SUCCESS";
export const PURCHASE_ORDER_FAILED = "PURCHASE_ORDER_FAILED";
export const PURCHASE_ORDER_START = "PURCHASE_ORDER_START";
export const PURCHASE_ORDER_INIT = "PURCHASE_INIT";
export const PURCHASE_ORDER_CLEAR = "PURCHASE_ORDER_CLEAR";
